import { AUTH_DEFAULT_STATE } from './authState'
import { ENVIRONMENT_VARIABLES } from './environment'
import {
  SIGN_IN_FORM_INITIAL_STATE,
  DEFAULT_TABLE_STATE,
  PRODUCT_FORM_INITIAL_STATE,
  PRODUCT_INTERIOR_FORM_INITIAL_STATE,
  CONFIGURE_PLATFORM_FORM_INITIAL_STATE,
} from './defaultState'
import { API_END_POINTS } from './endpoint'
import { APP_URL } from './appUrl'
import {
  DEFAULT_TABLE_HEADER,
  PRODUCT_TABLE_HEADER,
  SPECIFICATION_TABLE_HEADER,
  SPECIFICATION_CATEGORY_TABLE_HEADER,
  PRODUCT_CATEGORY_TABLE_HEADER,
  CONFIGURATION_PAINT_TABLE_HEADER,
  PRODUCT_INTERIOR_TABLE_HEADER,
  PRODUCT_SPECIFICATION_TABLE_HEADER,
  CONFIGURATION_WHEEL_TABLE_HEADER,
  CONFIGURATION_INTERIOR_COLOR_TABLE_HEADER,
  ORDER_TABLE_HEADER,
  ORDER_TABLE_ITEM_HEADER,
  ORDER_TABLE_PAYMENT_HEADER,
  CONFIGURATION_PLATFORM_TABLE_HEADER,
  QUOTATION_TABLE_HEADER,
  BROCHURE_TABLE_HEADER,
} from './dataTableHeader'
import { PRODUCT_PAGE_TAB } from './productPageTab'
import { STATUS_CHIP } from './chip'
import { PLATFORM_SECTION } from './platform'

export {
  AUTH_DEFAULT_STATE,
  ENVIRONMENT_VARIABLES,
  SIGN_IN_FORM_INITIAL_STATE,
  API_END_POINTS,
  APP_URL,
  DEFAULT_TABLE_STATE,
  DEFAULT_TABLE_HEADER,
  PRODUCT_TABLE_HEADER,
  SPECIFICATION_TABLE_HEADER,
  SPECIFICATION_CATEGORY_TABLE_HEADER,
  PRODUCT_CATEGORY_TABLE_HEADER,
  CONFIGURATION_PAINT_TABLE_HEADER,
  PRODUCT_INTERIOR_TABLE_HEADER,
  PRODUCT_SPECIFICATION_TABLE_HEADER,
  PRODUCT_PAGE_TAB,
  CONFIGURATION_WHEEL_TABLE_HEADER,
  CONFIGURATION_INTERIOR_COLOR_TABLE_HEADER,
  ORDER_TABLE_HEADER,
  STATUS_CHIP,
  ORDER_TABLE_ITEM_HEADER,
  ORDER_TABLE_PAYMENT_HEADER,
  PRODUCT_FORM_INITIAL_STATE,
  PRODUCT_INTERIOR_FORM_INITIAL_STATE,
  CONFIGURATION_PLATFORM_TABLE_HEADER,
  PLATFORM_SECTION,
  CONFIGURE_PLATFORM_FORM_INITIAL_STATE,
  QUOTATION_TABLE_HEADER,
  BROCHURE_TABLE_HEADER,
}